[settings]

[tools]
1password-cli = "latest"
acli = "latest"
bat = "latest"
bottom = "latest"
bun = "latest"
cargo-binstall = "latest"
eza = "latest"
erlang = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
git-filter-repo = "latest"
gleam = "latest"
go = "latest"
gum = "latest"
herdr = "latest"
hk = "latest"
hub = "latest"
hunk = "latest"
jj = "latest"
jq = "latest"
lazygit = "latest"
lua = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "24.14.0"
pandoc = "latest"
pkgx = "latest"
pkl = "latest"
pnpm = "latest"
python = "latest"
rg = "latest"
shellcheck = "latest"
stylua = "latest"
tlrc = "latest"
tmux = "latest"
"cargo:tokei" = "latest"
tree-sitter = "latest"
yazi = "latest"
zoxide = "latest"
