[snapshot]
max-new-file-size = "3MiB"

[fsmonitor]
backend = "watchman"

[user]
email = "mark@jaquith.me"
name = "Mark Jaquith"

[ui]
default-command = "log"

[aliases]
prewarm = ["util", "exec", "--", "jj-prewarm"]
